const carNames = {
  audi: 'Audi',
  baic: 'Baic',
  bmw: 'BMW',
  cadillac: 'Cadillac',
  changan: 'Changan',
  chery: 'Chery',
  chevrolet: 'Chevrolet',
  citroen: 'Citroen',
  daewoo: 'Daewoo',
  exeed: 'Exeed',
  ford: 'Ford',
  geely: 'Geely',
  haval: 'Haval',
  honda: 'Honda',
  hyundai: 'Hyundai',
  infiniti: 'Infiniti',
  jaguar: 'Jaguar',
  jeep: 'Jeep',
  jetour: 'Jetour',
  kia: 'Kia',
  landRover: 'Land Rover',
  lexus: 'Lexus',
  mazda: 'Mazda',
  mercedes: 'Mercedes',
  mitsubishi: 'Mitsubishi',
  nissan: 'Nissan',
  omoda: 'Omoda',
  opel: 'Opel',
  peugeot: 'Peugeot',
  porsche: 'Porsche',
  renault: 'Renault',
  skoda: 'Skoda',
  subaru: 'Subaru',
  suzuki: 'Suzuki',
  toyota: 'Toyota',
  volkswagen: 'Volkswagen',
  volvo: 'Volvo',
};

export const carsdata = [
  {
    type: carNames.audi,
    model: 'R8',
    year: 2019,
  },
  {
    type: carNames.baic,
    model: 'R8',
    year: 2018,
  },
  {
    type: carNames.bmw,
    model: 'R8',
    year: 2017,
  },
  {
    type: carNames.cadillac,
    model: 'R8',
    year: 2016,
  },
  {
    type: carNames.changan,
    model: 'R8',
    year: 2015,
  },
  {
    type: carNames.chery,
    model: 'R8',
    year: 2014,
  },
  {
    type: carNames.chevrolet,
    model: 'R8',
    year: 2013,
  },
  {
    type: carNames.citroen,
    model: 'R8',
    year: 2012,
  },
  {
    type: carNames.daewoo,
    model: 'R8',
    year: 2011,
  },
  {
    type: carNames.exeed,
    model: 'R8',
    year: 2010,
  },
  {
    type: carNames.ford,
    model: 'R8',
    year: 2019,
  },
  {
    type: carNames.geely,
    model: 'R8',
    year: 2019,
  },
  {
    type: carNames.haval,
    model: 'R8',
    year: 2019,
  },
  {
    type: carNames.honda,
    model: 'R8',
    year: 2019,
  },
  {
    type: carNames.hyundai,
    model: 'R8',
    year: 2019,
  },
  {
    type: carNames.infiniti,
    model: 'R8',
    year: 2019,
  },
  {
    type: carNames.jaguar,
    model: 'R8',
    year: 2019,
  },
  {
    type: carNames.jeep,
    model: 'R8',
    year: 2019,
  },
  {
    type: carNames.jetour,
    model: 'R8',
    year: 2019,
  },
  {
    type: carNames.kia,
    model: 'R8',
    year: 2019,
  },
  {
    type: carNames.landRover,
    model: 'R8',
    year: 2019,
  },
  {
    type: carNames.lexus,
    model: 'R8',
    year: 2019,
  },
  {
    type: carNames.mazda,
    model: 'R8',
    year: 2019,
  },
  {
    type: carNames.mercedes,
    model: 'R8',
    year: 2019,
  },
  {
    type: carNames.mitsubishi,
    model: 'R8',
    year: 2019,
  },
  {
    type: carNames.nissan,
    model: 'R8',
    year: 2019,
  },
  {
    type: carNames.omoda,
    model: 'R8',
    year: 2019,
  },
  {
    type: carNames.opel,
    model: 'R8',
    year: 2019,
  },
  {
    type: carNames.peugeot,
    model: 'R8',
    year: 2019,
  },
  {
    type: carNames.porsche,
    model: 'R8',
    year: 2019,
  },
  {
    type: carNames.renault,
    model: 'R8',
    year: 2019,
  },
  {
    type: carNames.skoda,
    model: 'R8',
    year: 2019,
  },
  {
    type: carNames.subaru,
    model: 'R8',
    year: 2019,
  },
  {
    type: carNames.suzuki,
    model: 'R8',
    year: 2019,
  },
  {
    type: carNames.toyota,
    model: 'R8',
    year: 2019,
  },
  {
    type: carNames.volkswagen,
    model: 'R8',
    year: 2019,
  },
  {
    type: carNames.volvo,
    model: 'R8',
    year: 2019,
  },
];
